version: "2.1"

services:
  database:
    extends:
      file: docker-compose.base.yml
      service: database-base
    ports:
      - "5433:5432"
    volumes:
      - ./data/database:/var/lib/postgresql/data

  database-testing:
    extends:
      file: docker-compose.base.yml
      service: database-base
    ports:
      - "5434:5432"
