version: "2.1"

services:
  database-base:
    # This is using PostgreSQL 10 because Flyway doesn't support cleaning PostgreSQL 11 yet: https://github.com/flyway/flyway/issues/2178
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=${artifactId}
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
